{% set name = "CRoaring" %}
{% set version = "4.3.7" %}
{% set sha256 = "57d96c566678087ba0ac248b9537c6df0d8600d1df9e38503121b42f22a382bd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RoaringBitmap/CRoaring/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('croaring', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja

test:
  commands:
    # headers
    - test -f $PREFIX/include/roaring/array_util.h                     # [unix]
    - test -f $PREFIX/include/roaring/bitset_util.h                    # [unix]
    - test -f $PREFIX/include/roaring/containers/array.h               # [unix]
    - test -f $PREFIX/include/roaring/containers/bitset.h              # [unix]
    - test -f $PREFIX/include/roaring/containers/containers.h          # [unix]
    - test -f $PREFIX/include/roaring/containers/convert.h             # [unix]
    - test -f $PREFIX/include/roaring/containers/mixed_andnot.h        # [unix]
    - test -f $PREFIX/include/roaring/containers/mixed_equal.h         # [unix]
    - test -f $PREFIX/include/roaring/containers/mixed_intersection.h  # [unix]
    - test -f $PREFIX/include/roaring/containers/mixed_negation.h      # [unix]
    - test -f $PREFIX/include/roaring/containers/mixed_subset.h        # [unix]
    - test -f $PREFIX/include/roaring/containers/mixed_union.h         # [unix]
    - test -f $PREFIX/include/roaring/containers/mixed_xor.h           # [unix]
    - test -f $PREFIX/include/roaring/containers/perfparameters.h      # [unix]
    - test -f $PREFIX/include/roaring/containers/run.h                 # [unix]
    - test -f $PREFIX/include/roaring/misc/configreport.h              # [unix]
    - test -f $PREFIX/include/roaring/portability.h                    # [unix]
    - test -f $PREFIX/include/roaring/roaring.h                        # [unix]
    - test -f $PREFIX/include/roaring/roaring_array.h                  # [unix]
    - test -f $PREFIX/include/roaring/roaring_types.h                  # [unix]
    - test -f $PREFIX/include/roaring/roaring_version.h                # [unix]
    - test -f $PREFIX/include/roaring/utilasm.h                        # [unix]
    - "if not exist %LIBRARY_INC%\\roaring\\array_util.h exit 1"                      # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\bitset_util.h exit 1"                     # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\array.h exit 1"               # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\bitset.h exit 1"              # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\containers.h exit 1"          # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\convert.h exit 1"             # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\mixed_andnot.h exit 1"        # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\mixed_equal.h exit 1"         # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\mixed_intersection.h exit 1"  # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\mixed_negation.h exit 1"      # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\mixed_subset.h exit 1"        # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\mixed_union.h exit 1"         # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\mixed_xor.h exit 1"           # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\perfparameters.h exit 1"      # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\containers\\run.h exit 1"                 # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\misc\\configreport.h exit 1"              # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\portability.h exit 1"                     # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\roaring.h exit 1"                         # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\roaring_array.h exit 1"                   # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\roaring_types.h exit 1"                   # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\roaring_version.h exit 1"                 # [win]
    - "if not exist %LIBRARY_INC%\\roaring\\utilasm.h exit 1"                         # [win]

    # shared libraries
    - test -f $PREFIX/lib/libroaring${SHLIB_EXT}        # [unix]
    - "if not exist %LIBRARY_BIN%\\roaring.dll exit 1"  # [win]

    # static libraries
    - "if not exist %LIBRARY_LIB%\\roaring.lib exit 1"  # [win]

about:
  home: https://github.com/RoaringBitmap/CRoaring
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    Portable Roaring bitmaps in C (and C++) with full support for your favorite compiler (GNU GCC, LLVM's clang, Visual Studio).
    Included in the Awesome C list of open source C software.

extra:
  recipe-maintainers:
    - bdice
    - cumbof
